In [2]:
import pandas as pd

In [ ]:
df=pd.read_csv(r"C:\Users\Shantanu\Downloads\Salary_Data.csv")
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [5]:
df['years']=df['YearsExperience'].astype(int) #to change data type

In [6]:
df['YearsExperience']=df['YearsExperience'].astype(int) #to change data type

In [7]:
df.head(5)

   YearsExperience   Salary  years
0                1  39343.0      1
1                1  46205.0      1
2                1  37731.0      1
3                2  43525.0      2
4                2  39891.0      2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     int32
 1   Salary           30 non-null     float64
 2   years            30 non-null     int32
dtypes: float64(1), int32(2)
memory usage: 612.0 bytes

In [12]:
df.drop('YearsExperience', axis=1, inplace=True) # axix 1 for column 0 for rows

KeyError: "['YearsExperience'] not found in axis"

In [13]:
df.head()

    Salary  years
0  39343.0      1
1  46205.0      1
2  37731.0      1
3  43525.0      2
4  39891.0      2

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Salary  30 non-null     float64
 1   years   30 non-null     int32
dtypes: float64(1), int32(1)
memory usage: 492.0 bytes

In [15]:
print('no of rows and column:',df.shape)

no of rows and column: (30, 2)

In [16]:
df.describe()

              Salary      years
count      30.000000  30.000000
mean    76003.000000   4.933333
std     27414.429785   2.790789
min     37731.000000   1.000000
25%     56720.750000   3.000000
50%     65237.000000   4.000000
75%    100544.750000   7.000000
max    122391.000000  10.000000

In [17]:
df.head()

    Salary  years
0  39343.0      1
1  46205.0      1
2  37731.0      1
3  43525.0      2
4  39891.0      2

In [18]:
from sklearn.model_selection import train_test_split

In [26]:
x= df.drop("Salary", axis=1) #independent variable
y= df["Salary"]

In [21]:
import statsmodels.api as sm

In [22]:
x_with_constant=sm.add_constant(x)
x_with_constant

    const  years
0     1.0      1
1     1.0      1
2     1.0      1
3     1.0      2
4     1.0      2
5     1.0      2
6     1.0      3
7     1.0      3
8     1.0      3
9     1.0      3
10    1.0      3
11    1.0      4
12    1.0      4
13    1.0      4
14    1.0      4
15    1.0      4
16    1.0      5
17    1.0      5
18    1.0      5
19    1.0      6
20    1.0      6
21    1.0      7
22    1.0      7
23    1.0      8
24    1.0      8
25    1.0      9
26    1.0      9
27    1.0      9
28    1.0     10
29    1.0     10

In [23]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [24]:
xtrain,xtest,ytrain,ytest= train_test_split(x_with_constant,y,test_size=0.3,random_state=30)

In [25]:
xtest.head()

    const  years
15    1.0      4
28    1.0     10
26    1.0      9
10    1.0      3
24    1.0      8

In [27]:
xtrain.index

Index([4, 11, 22, 18, 19, 1, 16, 7, 9, 3, 14, 17, 21, 2, 23, 12, 20, 27, 13,
       29, 5],
      dtype='int64')

In [28]:
model=sm.OLS(ytrain,xtrain).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     256.3
Date:                Mon, 23 Mar 2026   Prob (F-statistic):           1.74e-12
Time:                        19:50:14   Log-Likelihood:                -214.92
No. Observations:                  21   AIC:                             433.8
Df Residuals:                      19   BIC:                             435.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.624e+04   3298.359      7.954      0.000    1.93e+04    3.31e+04
years       9996.7047    624.394     16.010      0.000    8689.833    1.13e+04
==============================================================================
Omnibus:                        4.673   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                1.531
Skew:                          -0.077   Prob(JB):                        0.465
Kurtosis:                       1.686   Cond. No.                         11.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
#PREDICTION

In [31]:
pred_train=model.predict(xtrain)
pred_test=model.predict(xtest)

In [32]:
#MODEL METRICES

In [33]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [34]:
train_rmse=np.sqrt(mean_squared_error(ytrain,pred_train))
test_rmse=np.sqrt(mean_squared_error(ytest,pred_test))
print(f"Train_Rmse",train_rmse)
print(f"Test_Rmse",test_rmse)

Train_Rmse 6736.881910330945
Test_Rmse 5605.843473009092

In [35]:
#SK LEARN LINEAR REGRESSION

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
model_1=LinearRegression()
model_1.fit(xtrain,ytrain)

LinearRegression()

In [38]:
pred_train_1=model_1.predict(xtrain)
pred_test_1=model_1.predict(xtest)

In [39]:
pred_train_1

array([ 46228.93042191,  66222.33974833,  96212.45373797,  76219.04441155,
        86215.74907476,  36232.2257587 ,  76219.04441155,  56225.63508512,
        56225.63508512,  46228.93042191,  66222.33974833,  76219.04441155,
        96212.45373797,  36232.2257587 , 106209.15840118,  66222.33974833,
        86215.74907476, 116205.8630644 ,  66222.33974833, 126202.56772761,
        46228.93042191])

In [40]:
pred_test_1

array([ 66222.33974833, 126202.56772761, 116205.8630644 ,  56225.63508512,
       106209.15840118,  36232.2257587 ,  56225.63508512,  56225.63508512,
       116205.8630644 ])

In [41]:
df

      Salary  years
0    39343.0      1
1    46205.0      1
2    37731.0      1
3    43525.0      2
4    39891.0      2
5    56642.0      2
6    60150.0      3
7    54445.0      3
8    64445.0      3
9    57189.0      3
10   63218.0      3
11   55794.0      4
12   56957.0      4
13   57081.0      4
14   61111.0      4
15   67938.0      4
16   66029.0      5
17   83088.0      5
18   81363.0      5
19   93940.0      6
20   91738.0      6
21   98273.0      7
22  101302.0      7
23  113812.0      8
24  109431.0      8
25  105582.0      9
26  116969.0      9
27  112635.0      9
28  122391.0     10
29  121872.0     10