In [1]:
!pip install easygui

Requirement already satisfied: easygui in c:\users\hulaw\anaconda3\lib\site-packages (0.98.3)

In [ ]:
LINEAR REGRESSION PROJECT ON EMPLOYESS SALARY PREDICTION

In [3]:
import pandas as pd
import easygui

In [7]:
path=easygui.fileopenbox()

In [9]:
df=pd.read_csv("Salary_Data.csv")
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [11]:
df.shape

(30, 2)

In [13]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [19]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [25]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [31]:
df['years']=df['YearsExperience'].astype(int)  # to change the datatype

In [33]:
df['YearsExperience']=df['YearsExperience'].astype(int)

In [37]:
df.head()

   YearsExperience   Salary  years
0                1  39343.0      1
1                1  46205.0      1
2                1  37731.0      1
3                2  43525.0      2
4                2  39891.0      2

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     int32
 1   Salary           30 non-null     float64
 2   years            30 non-null     int32
dtypes: float64(1), int32(2)
memory usage: 612.0 bytes

In [41]:
df['Salary']=df['Salary'].astype(int)  # to change the datatype

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     int32
 1   Salary           30 non-null     int32
 2   years            30 non-null     int32
dtypes: int32(3)
memory usage: 492.0 bytes

In [45]:
df.drop('YearsExperience',axis=1,inplace=True)

In [47]:
df.head()

   Salary  years
0   39343      1
1   46205      1
2   37731      1
3   43525      2
4   39891      2

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Salary  30 non-null     int32
 1   years   30 non-null     int32
dtypes: int32(2)
memory usage: 372.0 bytes

In [51]:
print('Numbers of Rows and Columns: ',df.shape) # to find the shape of dataset

Numbers of Rows and Columns:  (30, 2)

In [53]:
df['years'].describe()

count    30.000000
mean      4.933333
std       2.790789
min       1.000000
25%       3.000000
50%       4.000000
75%       7.000000
max      10.000000
Name: years, dtype: float64

In [55]:
df.describe()

              Salary      years
count      30.000000  30.000000
mean    76003.000000   4.933333
std     27414.429785   2.790789
min     37731.000000   1.000000
25%     56720.750000   3.000000
50%     65237.000000   4.000000
75%    100544.750000   7.000000
max    122391.000000  10.000000

In [ ]:
Linear Regression Relies on several key assumptions for its validity. Here are the main assumption:
Linearity: The relationship between the dependent variable (Y) and the independent variable (X) is linear. This means tha the
change in Y is proportional to change in X.

Normality: The residuals are normally distributed. This means that the distribution of the residuals should resembel a bell curve when plotted.

No Perfect Multicollinearity: There should be no exact linear relationship between the independent variables. In other words, one independent variable should not be a perfect linear combination of the others.

Homoscedasticity: Also known as constant variance, this assumption states that the variance of the residuals (the difference between the observed and predicted values)
is constant accross all levels of the independent variable (s ). In simpler terms, the spread of the residuals should remain the same throughout the range of X.

No Autocorrelation: The residuals are not correlated with each other. This means that there is no pattern in the residuals when plotted
against time or the order in which they were collected.

In [57]:
df.head()

   Salary  years
0   39343      1
1   46205      1
2   37731      1
3   43525      2
4   39891      2

In [ ]:
MODEL DATA SPLIT

In [59]:
from sklearn.model_selection import train_test_split

In [61]:
x=df.drop("Salary",axis=1) # independent variables
y=df['Salary'] # target / dependent variable

In [63]:
import statsmodels.api as sm

In [65]:
x_with_constant=sm.add_constant(x)
x_with_constant

    const  years
0     1.0      1
1     1.0      1
2     1.0      1
3     1.0      2
4     1.0      2
5     1.0      2
6     1.0      3
7     1.0      3
8     1.0      3
9     1.0      3
10    1.0      3
11    1.0      4
12    1.0      4
13    1.0      4
14    1.0      4
15    1.0      4
16    1.0      5
17    1.0      5
18    1.0      5
19    1.0      6
20    1.0      6
21    1.0      7
22    1.0      7
23    1.0      8
24    1.0      8
25    1.0      9
26    1.0      9
27    1.0      9
28    1.0     10
29    1.0     10

In [ ]:
y = B0 + B1x (y=mx+c)

In [67]:
xtrain,xtest,ytrain,ytest=train_test_split(x_with_constant,y,test_size=0.3,random_state=30)

In [69]:
xtest.head()

    const  years
15    1.0      4
28    1.0     10
26    1.0      9
10    1.0      3
24    1.0      8

In [71]:
xtrain.index

Index([4, 11, 22, 18, 19, 1, 16, 7, 9, 3, 14, 17, 21, 2, 23, 12, 20, 27, 13,
       29, 5],
      dtype='int64')

In [ ]:
MODEL BUILDING

In [ ]:
import statsmodels.api as sm

In [ ]:
# statsmodel statistical model -- OLS (Ordinary Least Square)
# sklearn - linear regression

In [73]:
model=sm.OLS(ytrain,xtrain).fit()  # r squared value should be minimum
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     256.3
Date:                Mon, 23 Mar 2026   Prob (F-statistic):           1.74e-12
Time:                        19:48:33   Log-Likelihood:                -214.92
No. Observations:                  21   AIC:                             433.8
Df Residuals:                      19   BIC:                             435.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.624e+04   3298.359      7.954      0.000    1.93e+04    3.31e+04
years       9996.7047    624.394     16.010      0.000    8689.833    1.13e+04
==============================================================================
Omnibus:                        4.673   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                1.531
Skew:                          -0.077   Prob(JB):                        0.465
Kurtosis:                       1.686   Cond. No.                         11.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
PREDICTION

In [75]:
pred_train=model.predict(xtrain)
pred_test=model.predict(xtest)

In [ ]:
MODEL METRICES

In [79]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [83]:
train_rmse=np.sqrt(mean_squared_error(ytrain,pred_train))
test_rmse=np.sqrt(mean_squared_error(ytest,pred_test))
print(f"Train_Rmse",train_rmse)
print(f"Test_Rmse",test_rmse)

Train_Rmse 6736.881910330943
Test_Rmse 5605.84347300909

In [ ]:
SK LEARN LINEAR REGRESSION

In [89]:
from sklearn.linear_model import LinearRegression

In [91]:
model_1=LinearRegression()
model_1.fit(xtrain,ytrain)

LinearRegression()

In [93]:
pred_train_1=model_1.predict(xtrain)
pred_test_1=model_1.predict(xtest)

In [95]:
pred_train_1

array([ 46228.93042191,  66222.33974833,  96212.45373797,  76219.04441155,
        86215.74907476,  36232.2257587 ,  76219.04441155,  56225.63508512,
        56225.63508512,  46228.93042191,  66222.33974833,  76219.04441155,
        96212.45373797,  36232.2257587 , 106209.15840118,  66222.33974833,
        86215.74907476, 116205.8630644 ,  66222.33974833, 126202.56772761,
        46228.93042191])

In [97]:
pred_test_1

array([ 66222.33974833, 126202.56772761, 116205.8630644 ,  56225.63508512,
       106209.15840118,  36232.2257587 ,  56225.63508512,  56225.63508512,
       116205.8630644 ])

In [ ]:
witr conditional statement if else
student grade above 90 - a garde
above 80 -b
above 60 -c

In [103]:
Grade=float(input("Enter the grade: "))
if Grade>=90:
    print("A Grade")
elif Grade>=80:
    print("B Grade")
elif Grade>=60:
    print("C Grade")
else:
    print("D Grade")

Enter the grade:  90.5

A Grade

In [105]:
df

    Salary  years
0    39343      1
1    46205      1
2    37731      1
3    43525      2
4    39891      2
5    56642      2
6    60150      3
7    54445      3
8    64445      3
9    57189      3
10   63218      3
11   55794      4
12   56957      4
13   57081      4
14   61111      4
15   67938      4
16   66029      5
17   83088      5
18   81363      5
19   93940      6
20   91738      6
21   98273      7
22  101302      7
23  113812      8
24  109431      8
25  105582      9
26  116969      9
27  112635      9
28  122391     10
29  121872     10